export enum Subject {
  PORTUGUESE = "PORTUGUESE",
  MATHEMATICS = "MATHEMATICS",
  HISTORY = "HISTORY",
  GEOGRAPHY = "GEOGRAPHY",
  BIOLOGY = "BIOLOGY",
  PHYSICS = "PHYSICS",
  CHEMISTRY = "CHEMISTRY",
  ENGLISH = "ENGLISH",
  PHILOSOPHY = "PHILOSOPHY",
  SOCIOLOGY = "SOCIOLOGY",
  PHYSICAL_EDUCATION = "PHYSICAL_EDUCATION",
  ARTS = "ARTS"
}
