name: CI

on:
  push:
    branches:
      - main
      - develop
      - feat-testes-unitarios 
  pull_request:
    branches:
      - main
      - develop
      - feat-testes-unitarios 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar ESLint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Executar Testes Unitários e Cobertura
        run: npx jest --coverage

      - name: Build TypeScript
        run: npm run build